[features]
seeds = false
[programs.localnet]
luckyseven = "FcbmXvb6x3ahEktJMykvfnv2qKPowC1FcqhxD9aUac68"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/matiasbn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/tokens.ts"
